// Generated by scripts/mirror-types.ts from media-contract/schemas/media-v1.schema.json when
// npm run typegen runs. Don't edit it.
//
// The mirror documents as media-ops writes them: every field the contract requires, with its
// null states. sanity.types.ts types the same documents as Studio's form sees them, with every
// field optional and never null. Read mirror documents with these types.

/** Section 3. Written only by media-ops. Never deleted; a tombstone has public false. */
export type MediaReleaseDocument = {
  mirrorGen: number
  mirrorSeq: number
  _id: string
  _type: 'mediaRelease'
  _rev?: string
  _createdAt?: string
  _updatedAt?: string
  environment: 'dev' | 'staging' | 'production'
  contentId: string
  /** Null only on a tombstone created for an absent source */
  kind: 'video' | 'nonvideo' | null
  public: boolean
  assetId: string | null
  playbackId: string | null
  durationSeconds: number | null
  captions: Array<{
    /** Erratum E21. Sanity's array item key, unique within the array. media-ops writes the item's language. The public API never returns it. */
    _key?: string
    language: string
    label: string
    kind: 'live' | 'generated' | 'uploaded'
    state: 'requested' | 'processing' | 'available'
  }>
  publishedAt: string | null
  releaseVersion: number | null
}

/** Section 3. Written only by media-ops. playback is null until playableFrom and while takenDown. */
export type LiveStatusDocument = {
  mirrorGen: number
  mirrorSeq: number
  _id: string
  _type: 'liveStatus'
  _rev?: string
  _createdAt?: string
  _updatedAt?: string
  environment: 'dev' | 'staging' | 'production'
  channel: string
  resourceId: string | null
  sessionState:
    | 'armed'
    | 'connecting'
    | 'live'
    | 'reconnecting'
    | 'interrupted'
    | 'ending'
    | 'ended'
    | 'abandoned'
    | 'cancelled'
    | null
  takenDown: boolean
  playableFrom: string | null
  endedAt: string | null
  event: {
    eventId: string
    contentId: string
    title: string
    scheduledStart: string
    seriesTitle: string | null
  } | null
  nextEvent: {
    eventId: string
    contentId: string
    title: string
    scheduledStart: string
    seriesTitle: string | null
  } | null
  playback: {
    hls: string
    /** Live has no trick play, so the Roku URL never carries roku_trick_play */
    hlsRoku: string
    expiresAt: string
  } | null
  observedAt: string | null
  staleAfterSeconds: 180 | 2700
}
